# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/z4u/setup-makefiles.sh

PRODUCT_COPY_FILES += \
  vendor/htc/z4u/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
  vendor/htc/z4u/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
  vendor/htc/z4u/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
  vendor/htc/z4u/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
  vendor/htc/z4u/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/htc/z4u/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
  vendor/htc/z4u/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
  vendor/htc/z4u/proprietary/lib/libgsl.so:system/lib/libgsl.so \
  vendor/htc/z4u/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
  vendor/htc/z4u/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
  vendor/htc/z4u/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
  vendor/htc/z4u/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
  vendor/htc/z4u/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
  vendor/htc/z4u/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
  vendor/htc/z4u/proprietary/lib/libv8.so:system/lib/libv8.so \
  vendor/htc/z4u/proprietary/bin/abtfilt:system/bin/abtfilt \
  vendor/htc/z4u/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
  vendor/htc/z4u/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
  vendor/htc/z4u/proprietary/lib/libchromatix_s5k6a1gx_default_video.so:system/lib/libchromatix_s5k6a1gx_default_video.so \
  vendor/htc/z4u/proprietary/lib/libchromatix_s5k6a1gx_hdr.so:system/lib/libchromatix_s5k6a1gx_hdr.so \
  vendor/htc/z4u/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
  vendor/htc/z4u/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/htc/z4u/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/htc/z4u/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/htc/z4u/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/htc/z4u/proprietary/lib/hw/camera.msm7627a.so:system/lib/hw/camera.msm7627a.so \
  vendor/htc/z4u/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
  vendor/htc/z4u/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
  vendor/htc/z4u/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/htc/z4u/proprietary/lib/libposteffect.so:system/lib/libposteffect.so \
  vendor/htc/z4u/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
  vendor/htc/z4u/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
  vendor/htc/z4u/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
  vendor/htc/z4u/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
  vendor/htc/z4u/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
  vendor/htc/z4u/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
  vendor/htc/z4u/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
  vendor/htc/z4u/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
  vendor/htc/z4u/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
  vendor/htc/z4u/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
  vendor/htc/z4u/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
  vendor/htc/z4u/proprietary/bin/abtfilt:system/bin/abtfilt \
  vendor/htc/z4u/proprietary/bin/cand:system/bin/cand \
  vendor/htc/z4u/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
  vendor/htc/z4u/proprietary/bin/hdmid:system/bin/hdmid \
  vendor/htc/z4u/proprietary/bin/pnpmgr:system/bin/pnpmgr \
  vendor/htc/z4u/proprietary/bin/sdptool:system/bin/sdptool \
  vendor/htc/z4u/proprietary/bin/zchgd:system/bin/zchgd \
  vendor/htc/z4u/proprietary/bin/charging:system/bin/charging \
  vendor/htc/z4u/proprietary/bin/mpdecision:system/bin/mpdecision \
  vendor/htc/z4u/proprietary/bin/netsharing:system/bin/netsharing \
  vendor/htc/z4u/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/htc/z4u/proprietary/bin/thermald:system/bin/thermald \
  vendor/htc/z4u/proprietary/bin/rild:system/bin/rild \
  vendor/htc/z4u/proprietary/bin/htc_ebdlogd:system/bin/htc_ebdlogd \
  vendor/htc/z4u/proprietary/lib/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
  vendor/htc/z4u/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
  vendor/htc/z4u/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/htc/z4u/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/htc/z4u/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/htc/z4u/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/htc/z4u/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/htc/z4u/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/htc/z4u/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/htc/z4u/proprietary/lib/libgsl.so:system/lib/libgsl.so \
  vendor/htc/z4u/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/htc/z4u/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
  vendor/htc/z4u/proprietary/lib/libv8.so:system/lib/libv8.so \
  vendor/htc/z4u/proprietary/lib/hw/sensors.msm7627a.so:system/lib/hw/sensors.msm7627a.so \
  vendor/htc/z4u/proprietary/bin/hostapd:system/bin/hostapd \
  vendor/htc/z4u/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin \
  vendor/htc/z4u/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/athwlan.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/athwlan.bin \
  vendor/htc/z4u/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin \
  vendor/htc/z4u/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin \
  vendor/htc/z4u/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/nullTestFlow.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/nullTestFlow.bin \
  vendor/htc/z4u/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/utf.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/utf.bin \
  vendor/htc/z4u/proprietary/lib/modules/ath6kl_sdio.ko:system/lib/modules/ath6kl_sdio.ko \
  vendor/htc/z4u/proprietary/lib/modules/cfg80211.ko:system/lib/modules/cfg80211.ko
