# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/z4u/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries

PRODUCT_COPY_FILES += \
  vendor/htc/z4u/proprietary/etc/agps_rm:system/etc/agps_rm \
  vendor/htc/z4u/proprietary/bin/charging:system/bin/charging \
  vendor/htc/z4u/proprietary/bin/mpdecision:system/bin/mpdecision \
  vendor/htc/z4u/proprietary/bin/netsharing:system/bin/netsharing \
  vendor/htc/z4u/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/htc/z4u/proprietary/bin/thermald:system/bin/thermald \
  vendor/htc/z4u/proprietary/lib/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
  vendor/htc/z4u/proprietary/lib/hw/camera.msm7627a.so:system/lib/hw/camera.msm7627a.so \
  vendor/htc/z4u/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
  vendor/htc/z4u/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
  vendor/htc/z4u/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/htc/z4u/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/htc/z4u/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/htc/z4u/proprietary/lib/libposteffect.so:system/lib/libposteffect.so \
  vendor/htc/z4u/proprietary/lib/libchromatix_s5k6a1gx_default_video.so:system/lib/libchromatix_s5k6a1gx_default_video.so \
  vendor/htc/z4u/proprietary/lib/libchromatix_s5k6a1gx_hdr.so:system/lib/libchromatix_s5k6a1gx_hdr.so \
  vendor/htc/z4u/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
  vendor/htc/z4u/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
  vendor/htc/z4u/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/htc/z4u/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
  vendor/htc/z4u/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
  vendor/htc/z4u/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
  vendor/htc/z4u/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
  vendor/htc/z4u/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/htc/z4u/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/htc/z4u/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/htc/z4u/proprietary/lib/libgsl.so:system/lib/libgsl.so \
  vendor/htc/z4u/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/htc/z4u/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/htc/z4u/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
  vendor/htc/z4u/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/htc/z4u/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/htc/z4u/proprietary/lib/libv8.so:system/lib/libv8.so \
  vendor/htc/z4u/proprietary/lib/libhtc_ril.so:system/lib/libhtc_ril.so \
  vendor/htc/z4u/proprietary/lib/hw/sensors.msm7627a.so:system/lib/hw/sensors.msm7627a.so
